### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by igormcsouza** [MRB-Computer-Vision/web-backend-admin#4]
https://github.com/MRB-Computer-Vision/web-backend-admin/blob/c311fd45e966f81a2ed34d6352146363c7da478b/app/main/util/dto.py#L39

```
Traceback (most recent call last):
app_1        |   File "manage.py", line 4, in <module>
app_1        |     from app import blueprint
app_1        |   File "/usr/src/app/app/__init__.py", line 8, in <module>
app_1        |     from .main.controllers.user_controller import api as user_ns
app_1        |   File "/usr/src/app/app/main/controllers/user_controller.py", line 5, in <module>
app_1        |     from ..util.dto import UserDto
app_1        |   File "/usr/src/app/app/main/util/dto.py", line 39
app_1        |     'files': fields.(required=False, description='user check if is active'),
app_1        |                     ^
app_1        | SyntaxError: invalid syntax
```

Hey! Assim que rodei a aplicação me encontrei com esse erro.. e realmente... `fields.()` não parece muito certo! Estou revendo aqui para ver se consigo concertar, mas já estou iniciando a issue anyway!

**Comment by igormcsouza** [comment]
Resolvi! Colocando como Boolean! Pelo visto é esse... Vou deixar o issue aberto para confirmação!

**Comment by igormcsouza** [comment]
Foi resolvido no PR #3
